import urllib.request
import json
import os

api_key = "AIzaSyAZAcGXcHpLZYPlDZclj_FIoT1ILWYpXRg"
url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?key={api_key}"

prompt = """
This is an Indian vehicle document (e.g., Insurance Policy, PUC/Pollution Certificate, Certificate of Fitness, RC). \
Extract the following information carefully. Terminology varies wildly: \
- 'documentNo': Policy No., Certificate SL. No., Application No, Receipt No, etc. \
- 'issuedDate': Date of Issue, Period of cover start date, Date, Inspected on, Receipt Date. \
- 'expiryDate': Period of cover end date, Validity upto, Certificate will expire on, Valid till, Next Inspection Due Date. \
Respond ONLY in this exact JSON format with no other text (ensure dates are strictly YYYY-MM-DD):
{
    "documentType": "insurance|gate_pass|puc|fitness|tax|state_permit|other",
    "documentNo": "extracted document number or null",
    "vehicleNo": "vehicle registration number (e.g. JH09...) or null",
    "issuedDate": "YYYY-MM-DD or null",
    "expiryDate": "YYYY-MM-DD or null",
    "confidence": "high|medium|low"
}
If you cannot read a field clearly, use null. documentType must \
be exactly one of the given values.

Here is the document text:
Policy No. : 54040031250100001919	Document generated by QR_RENEWAL at 2025/10/03 21:27:08.
Period of cover 07/10/2025 12:00:01 AM to 06/10/2026 11:59:59 PM
Registration no. JH-09-AB-1075
"""

data = {
    "contents": [{"parts": [{"text": prompt}]}]
}
req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'), headers={'Content-Type': 'application/json'})
try:
    with urllib.request.urlopen(req) as response:
        print(response.read().decode('utf-8'))
except Exception as e:
    print(e.read().decode('utf-8'))
