-- Module 1: Fleet & Operations - initial schema
-- Written to be compatible with both H2 (dev) and PostgreSQL (prod)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    full_name     VARCHAR(150),
    role          VARCHAR(30)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL
);

CREATE TABLE vehicles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number  VARCHAR(50) NOT NULL UNIQUE,
    vehicle_type         VARCHAR(50) NOT NULL,
    make                 VARCHAR(100),
    model                VARCHAR(100),
    capacity             VARCHAR(50),
    ownership_type       VARCHAR(30) NOT NULL,
    status               VARCHAR(30) NOT NULL,
    purchase_date        DATE,
    created_at           TIMESTAMP   NOT NULL,
    updated_at           TIMESTAMP   NOT NULL
);

CREATE TABLE operators (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    license_number  VARCHAR(50)  NOT NULL UNIQUE,
    phone           VARCHAR(20),
    address         VARCHAR(255),
    status          VARCHAR(30)  NOT NULL,
    joining_date    DATE,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

CREATE TABLE parties (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    party_type       VARCHAR(30)  NOT NULL,
    contact_person   VARCHAR(150),
    phone            VARCHAR(20),
    email            VARCHAR(150),
    address          VARCHAR(255),
    gst_number       VARCHAR(30),
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL
);

CREATE TABLE work_orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_number    VARCHAR(50)  NOT NULL UNIQUE,
    party_id             BIGINT       REFERENCES parties(id),
    vehicle_id           BIGINT       REFERENCES vehicles(id),
    operator_id          BIGINT       REFERENCES operators(id),
    description          VARCHAR(1000),
    start_date           DATE,
    end_date             DATE,
    status               VARCHAR(30)  NOT NULL,
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL
);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name    VARCHAR(100) NOT NULL,
    entity_id      VARCHAR(50),
    action         VARCHAR(30)  NOT NULL,
    performed_by   VARCHAR(100),
    details        VARCHAR(2000),
    created_at     TIMESTAMP    NOT NULL
);

CREATE INDEX idx_work_orders_party_id ON work_orders(party_id);
CREATE INDEX idx_work_orders_vehicle_id ON work_orders(vehicle_id);
CREATE INDEX idx_work_orders_operator_id ON work_orders(operator_id);
CREATE INDEX idx_audit_log_entity ON audit_log(entity_name, entity_id);
