-- Module 1: Fleet & Operations - daily logs, trip/diesel tracking, vehicle documents
-- Written to be compatible with both H2 (dev) and PostgreSQL (prod).
-- FKs reference the unqualified tables created in V1 (no "core" schema exists).

CREATE TABLE jcb_daily_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE         NOT NULL,
    vehicle_id          BIGINT       REFERENCES vehicles(id),
    work_order_id       BIGINT       REFERENCES work_orders(id),
    operator_id         BIGINT       REFERENCES operators(id),
    opening_hrs         NUMERIC(8,1),
    closing_hrs         NUMERIC(8,1),
    total_hrs           NUMERIC(8,1),
    diesel_ltr          NUMERIC(8,2),
    diesel_mtr          NUMERIC(8,1),
    running_ltr         NUMERIC(8,2),
    avg_ltr_per_hr      NUMERIC(6,2),
    material_type       VARCHAR(50),
    material_qty        NUMERIC(10,2),
    material_unit       VARCHAR(20),
    work_description    TEXT,
    receiving_slip_url  VARCHAR(500),
    status              VARCHAR(20)  NOT NULL DEFAULT 'submitted',
    submitted_by        BIGINT       REFERENCES users(id),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jcb_daily_log_shifts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id      BIGINT     REFERENCES jcb_daily_log(id) ON DELETE CASCADE,
    start_time  TIME       NOT NULL,
    close_time  TIME       NOT NULL,
    total_time  NUMERIC(5,2)
);

CREATE TABLE tipper_daily_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE         NOT NULL,
    vehicle_id          BIGINT       REFERENCES vehicles(id),
    work_order_id       BIGINT       REFERENCES work_orders(id),
    driver_id           BIGINT       REFERENCES operators(id),
    opening_hrs         NUMERIC(8,1),
    closing_hrs         NUMERIC(8,1),
    total_hrs           NUMERIC(8,1),
    opening_km          NUMERIC(10,1),
    closing_km          NUMERIC(10,1),
    total_km            NUMERIC(10,1),
    diesel_ltr          NUMERIC(8,2),
    diesel_hrs          NUMERIC(8,1),
    diesel_km           NUMERIC(10,1),
    run_km              NUMERIC(10,1),
    avg_km_per_ltr      NUMERIC(6,2),
    trip_count          INT          DEFAULT 0,
    work_description    TEXT,
    receiving_slip_url  VARCHAR(500),
    status              VARCHAR(20)  NOT NULL DEFAULT 'submitted',
    submitted_by        BIGINT       REFERENCES users(id),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tipper_trip_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id          BIGINT       REFERENCES tipper_daily_log(id) ON DELETE CASCADE,
    from_location   VARCHAR(200),
    to_location     VARCHAR(200),
    trips           INT          DEFAULT 1
);

CREATE TABLE tipper_hr_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id          BIGINT       REFERENCES tipper_daily_log(id) ON DELETE CASCADE,
    opening_hrs     NUMERIC(8,1),
    closing_hrs     NUMERIC(8,1),
    total_hrs       NUMERIC(8,1)
);

CREATE TABLE diesel_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE         NOT NULL,
    vehicle_id      BIGINT       REFERENCES vehicles(id),
    litres          NUMERIC(8,2) NOT NULL,
    received_from   VARCHAR(200),
    invoice_no      VARCHAR(100),
    slip_url        VARCHAR(500),
    entered_by      BIGINT       REFERENCES users(id),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id          BIGINT       REFERENCES vehicles(id),
    document_type       VARCHAR(50),
    document_no         VARCHAR(100),
    issued_date         DATE,
    expiry_date         DATE         NOT NULL,
    document_url        VARCHAR(500),
    ai_parsed_data      TEXT,
    reminder_sent_at    TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_jcb_daily_log_vehicle_id ON jcb_daily_log(vehicle_id);
CREATE INDEX idx_jcb_daily_log_work_order_id ON jcb_daily_log(work_order_id);
CREATE INDEX idx_jcb_daily_log_shifts_log_id ON jcb_daily_log_shifts(log_id);
CREATE INDEX idx_tipper_daily_log_vehicle_id ON tipper_daily_log(vehicle_id);
CREATE INDEX idx_tipper_daily_log_work_order_id ON tipper_daily_log(work_order_id);
CREATE INDEX idx_tipper_trip_entries_log_id ON tipper_trip_entries(log_id);
CREATE INDEX idx_tipper_hr_entries_log_id ON tipper_hr_entries(log_id);
CREATE INDEX idx_diesel_receipts_vehicle_id ON diesel_receipts(vehicle_id);
CREATE INDEX idx_vehicle_documents_vehicle_id ON vehicle_documents(vehicle_id);
CREATE INDEX idx_vehicle_documents_expiry_date ON vehicle_documents(expiry_date);
