-- Records every outbound notification attempt (email/whatsapp), even while
-- the underlying provider integration is a stub.

CREATE TABLE notification_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(20)  NOT NULL,
    recipient      VARCHAR(200) NOT NULL,
    subject        VARCHAR(255),
    message        TEXT,
    status         VARCHAR(20)  NOT NULL,
    sent_at        TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notification_log_recipient ON notification_log(recipient);
